server:
  servlet:
    context-path: /banco/api


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

  spring:
    flyway:
      locations: classpath:db/migration,classpath:db/testdata
